name: Warn on pushing to `release`
on:
  pull_request_target:
    types: [opened]
    branches: [release]
permissions:
  issues: write
jobs:
  comment:
    uses: MithrilJS/infra/.github/workflows/reject-pr.yml@main
    secrets: inherit
    with:
      correct_branch: next
