name: test

on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  contents: read

jobs:
  run-tests:
    uses: MithrilJS/infra/.github/workflows/run-tests.yml@main
    with:
      all-platforms: true
      all-versions: true
